# Generated by Django 5.0.1 on 2024-01-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("author_quote", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="quote",
            name="tags",
            field=models.ManyToManyField(to="author_quote.tag"),
        ),
    ]
